language: python
python:
  - 2.6
  - 2.7
install:
  - sudo apt-get update -yq2
  - sudo apt-get install -yq2 --no-install-recommends dvipng graphviz imagemagick lilypond source-highlight texlive-latex-base apt-show-versions
  - apt-show-versions python docbook-xsl-doc-text xsltproc w3m dblatex fop aap # for the readme
script:
  - python tests/testasciidoc.py update
  - python asciidoc.py --doctest
  - python asciidocapi.py
  - python tests/testasciidoc.py run
